name:                site-generator
version:             0.1.0.0
github:              "brenoafb/site-generator"
license:             BSD3
author:              "Breno Fatureto"
maintainer:          "breno.afb@gmail.com"
copyright:           "2021 Breno Fatureto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brenoafb/site-generator#readme>

dependencies:
- base >= 4.7 && < 5
- commonmark
- scotty
- http-types
- text
- aeson
- mtl
- directory

library:
  source-dirs: src

executables:
  site-generator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - site-generator

tests:
  site-generator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - site-generator
